// SPDX-License-Identifier: LGPL-2.1-or-later
import {POINTER_SIZE,HEADER_SIZE,WAVE_MAPPER,WHDR_DONE,check,waveFormat,readHandle,waveHeader} from "./native.js";
export class WaveInSource{
  constructor(lib,spec){this.lib=lib;this.closed=false;this.buffers=[];this.handleStorage=new Uint8Array(POINTER_SIZE);this.format=waveFormat(spec);check(lib.symbols.waveInOpen(this.handleStorage,WAVE_MAPPER,this.format,null,null,0),"waveInOpen");this.handle=readHandle(this.handleStorage);this.stdout=new ReadableStream({start:controller=>this.controller=controller});for(let i=0;i<4;i++)this.add(new Uint8Array(Math.ceil(spec.rate*spec.channels*2/50)));check(lib.symbols.waveInStart(this.handle),"waveInStart");this.poll();}
  add(data){const header=waveHeader(data);check(this.lib.symbols.waveInPrepareHeader(this.handle,header,HEADER_SIZE),"waveInPrepareHeader");check(this.lib.symbols.waveInAddBuffer(this.handle,header,HEADER_SIZE),"waveInAddBuffer");this.buffers.push({data,header});}
  poll(){if(this.closed)return;for(const item of this.buffers){const v=new DataView(item.header.buffer);if(v.getUint32(POINTER_SIZE+16,true)&WHDR_DONE){const bytes=v.getUint32(POINTER_SIZE+4,true);this.lib.symbols.waveInUnprepareHeader(this.handle,item.header,HEADER_SIZE);if(bytes)this.controller.enqueue(item.data.slice(0,bytes));item.header=waveHeader(item.data);check(this.lib.symbols.waveInPrepareHeader(this.handle,item.header,HEADER_SIZE),"waveInPrepareHeader");check(this.lib.symbols.waveInAddBuffer(this.handle,item.header,HEADER_SIZE),"waveInAddBuffer");}}this.timer=setTimeout(()=>this.poll(),5);}
  close(){if(this.closed)return;this.closed=true;clearTimeout(this.timer);this.lib.symbols.waveInStop(this.handle);this.lib.symbols.waveInReset(this.handle);for(const item of this.buffers)this.lib.symbols.waveInUnprepareHeader(this.handle,item.header,HEADER_SIZE);this.lib.symbols.waveInClose(this.handle);this.controller.close();}
  kill(){this.close();}
}
